### ISSUE TITLE
[FlexFields] Doesn't work for content types that already exist

### ISSUE THREAD

**Issue by rdgh01** [contentful/marketplace-partner-apps#1366]
**Describe the bug**
Apologies if I have missed something from the instructions but Flexfields doesn't work for me for content types that already existed before Flexfields was installed. I have tested on a test content type created after Flexfields was installed and it works fine. I would like to install Flexfields on a production site which has been running for a while so I would need it work on content types that already exist.

**Steps to reproduce**
1. Install FlexFields to a production environment
2. Add the FlexFields entry editor to a content type that existed before FlexFields was installed
3. Look at a content entry and see that under the FlexFields entry editor there are no fields showing

**Expected result**
All the fields should show in the FlexFields entry editor

**Screenshot**
![Screenshot 2024-04-02 161749](https://github.com/contentful/marketplace-partner-apps/assets/165812660/0214e4e1-0674-4d6c-8bcf-a2c6ae15df97)

**Comment by rdgh01** [comment]
I think I have been able to narrow this down to content types that have a JSON field type. This happens regardless of whether you select a custom appearance APP or the default object. Hopefully that helps?

**Comment by vipulchadda** [comment]
@rdgh01 Thanks for raising this issue and narrowing it down to JSON field type. 
Looks like there was an issue raised for this in the default field editors repository related to JSON editor: https://github.com/contentful/field-editors/issues/1458
@whitelisab @lilbitner would you be able to help with this?

**Comment by vipulchadda** [comment]
@rdgh01 This should be fixed now. Can you please confirm from your side?

**Comment by rdgh01** [comment]
hey @vipulchadda - I can confirm that is working now. Thank you!
