### ISSUE TITLE
[FlexFields] Bulk editor fields are very narrow.

### ISSUE THREAD

**Issue by vipulchadda** [contentful/marketplace-partner-apps#1588]
**Describe the bug**
When a field has `Bulk Edit` set to true, the fields in the bulk editor are very narrow (width is being set to 300px). 
This seems to be an existing issue with the app framework: https://github.com/contentful/ui-extensions-sdk/issues/1844

_[This was raised via support email. Creating here for tracking]_

**To Reproduce**
1. Enable `Bulk Edit` for multi-reference field
2. Open any content in the FlexFields editor (or any custom entry editor)
3. Click on the referenced entry
4. The fields in bulk editor are very narrow

**Expected behavior**
The fields should be displayed with default width.

**Screenshots**
![image](https://github.com/contentful/marketplace-partner-apps/assets/31496466/546fe6aa-553b-4230-ba68-b4805eb692ea)

**Comment by ethan-ozelius-contentful** [comment]
Taking a look at this.

**Comment by ethan-ozelius-contentful** [comment]
Hello @vipulchadda, thank you for raising this ticket.

This issue should have been resolved a few days ago, and we are unable to reproduce.  Are you still experiencing this bug?  If so, is there some more context/information you could share with us?  Perhaps the specific CSS (Maybe outside the iFrame) that might be causing this issue? 

I followed these steps to reproduce, but was unable to observe the behavior described in this ticket.

1. create a "Parent" content type that has a "multi-references" field
2. create a "child" content type that will be referenced.
3. create 3-4 child entries.
4. create a single parent entry, and in the multi-references field, add the children and create a couple new child entries, using FlexFields, as well as the default entry editor.

Any information would be appreciated.

**Comment by vipulchadda** [comment]
Yes, I do see this issue is resolved as well. Thank you for looking into this. Will go ahead and close this bug.

**Comment by ethan-ozelius-contentful** [comment]
> Yes, I do see this issue is resolved as well. Thank you for looking into this. Will go ahead and close this bug.

Awesome!  Glad to hear that!

Thanks!
