### ISSUE TITLE
[Optimizely] New auth path for account blocks temporary the Contentful App to auth successfully for Organisation 

### ISSUE THREAD

**Issue by juancarlosjr97** [contentful/marketplace-partner-apps#2261]
**Describe the bug**

Optimizely has a new auth flow that takes you from https://app.optimizely.com/ to login.optimizely.com.

The issue is that when the Auth flow is triggered the https://app.optimizely.com/ contains the callback URL but when the user clicks on [login.optimizely.com](https://login.optimizely.com/) the whole auth call back is lost as part of the redirect.

![Screenshot 2024-07-08 at 11 33 59 AM](https://github.com/contentful/marketplace-partner-apps/assets/36451129/c3b42354-8d21-4007-98b2-70ee7f038708)

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to Contentful and try to log in to Optimizely
2. Logged in will be successful but the auth with Optimizely and Contentful will not occur
3. Try clearing and cache multiple times and then it gets fixed
4. After the session has expired, the issue returns until multiple cache clear

**Expected behavior**

Auth with Contentful app works regardless of the auth path within Optimizely

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14.5 (23F79)
 - Browser - Chrome Version 126.0.6478.127 (Official Build) (arm64)
 - Version - Latest of Contentful and Optimizely app

**Additional context**

Additional information: https://www.contentful.com/marketplace/app/optimizely/ the app source code takes to the probably the migration app when moving to the full stack from the legacy Optimizely https://github.com/raju-opti/contentful-deploy/tree/master/apps/optimizely

**Comment by whitelisab** [comment]
Hi @juancarlosjr97, thanks for reporting this issue. We are connecting with the Optimizely team to look into this issue and we will get back to you when we have an update.

**Comment by russell-loube-optimizely** [comment]
Hi @juancarlosjr97 , this is Russell from the Optimizely team. I'm happy to report that this issue has been resolved after deploying a change on Optimizely's end.

Could you please confirm that you're once again able to login into the Optimizely app in Contentful? I'll look to @whitelisab to close this issue when appropriate (I don't have such permissions in this repo). Thanks all!

**Comment by juancarlosjr97** [comment]
Hi @russell-loube-optimizely , it looks like it is working without any issues :) 

Thank you for fixing it!
