### ISSUE TITLE
[FlexFields] Formatting and custom ui extensions not carrying over

### ISSUE THREAD

**Issue by perenstrom** [contentful/marketplace-partner-apps#707]
**Describe the bug**
Split from #642, see original issue for discussion.

## Large text markdown editor doesn't show any content at all (preview tab displays text ok)
**MAJOR** issue. Large text set to markdown editor doesn't show any content.

**Editor:**
![CleanShot 2024-01-15 at 10 35 31](https://github.com/contentful/marketplace-partner-apps/assets/765759/679ebbc4-4669-4b17-9e3d-f9ae7e59a81d)

**FlexFields:**
![CleanShot 2024-01-15 at 10 35 21](https://github.com/contentful/marketplace-partner-apps/assets/765759/8541d2a5-a47a-451d-b5b2-f43d288cdfaf)

## No support for multiple locales, only viewing default language regardless of selected locale
**MAJOR** issue. No support for multiple locales at all. It only shows default language.

**Editor:**
![CleanShot 2024-01-15 at 10 33 59](https://github.com/contentful/marketplace-partner-apps//assets/765759/8f839bb8-8ab8-4f01-b9ef-e3fa3e37feb9)

**FlexFields:**
![CleanShot 2024-01-15 at 10 34 05](https://github.com/contentful/marketplace-partner-apps/assets/765759/85e3565c-8441-4325-bfc7-a3aba7e2682d)

## Custom UI Extensions doesn't render at all

**Editor:**
![CleanShot 2024-01-15 at 10 32 49](https://github.com/contentful/marketplace-partner-apps/assets/765759/2f3b1f26-f7b3-46aa-85f6-544238786432)

**FlexFields:**
![CleanShot 2024-01-15 at 10 32 56](https://github.com/contentful/marketplace-partner-apps/assets/765759/eb20f76d-b69c-4921-91a1-5031a68053e5)

## Field headings are still light grey, instead of black as in normal editor (makes readability worse)
Headings and additional texts for fields are not the same colour as in the default editor, making contrast and readability worse.

**Editor:**
![CleanShot 2024-01-15 at 10 31 24](https://github.com/contentful/marketplace-partner-apps/assets/765759/9f459ca7-b4a6-446f-9833-78d2e9559126)

**FlexFields:**
![CleanShot 2024-01-15 at 10 31 15](https://github.com/contentful/marketplace-partner-apps/assets/765759/dafe1de7-7351-4b56-b217-4c01dc236396)

## Relation fields are in a different style (minor)
And a minor mismatch in the way linked entries are displayed.

**Editor:**
![CleanShot 2024-01-15 at 10 36 34](https://github.com/contentful/marketplace-partner-apps/assets/765759/3eb6df90-cbae-49ed-999b-bba77fb277d4)

**FlexFields:**
![CleanShot 2024-01-15 at 10 36 40](https://github.com/contentful/marketplace-partner-apps/assets/765759/3760e466-6abb-4e46-a074-4fb2c7783c24)

**Comment by lilbitner** [comment]
@vipulchadda for reference, this is the new issue created carried over from the last closed issue!

**Comment by vipulchadda** [comment]
Thanks. We are looking into these issues and will get back once we have any fixes/more information.

FYI, there is an open issue regarding the difference in the default field editors: https://github.com/contentful/field-editors/issues/1465. This might be the reason for the difference in title colour but we will still look into it from our side as well.

**Comment by vipulchadda** [comment]
@perenstrom These issues are fixed and are now deployed. Can you verify on your end and close this ticket if everything is working fine.
1 thing to note is that the Contentful app framework does not support referencing/importing an app within another app. So any field that is configured to use a custom app widget will display the default widget in FlexFields and we have added a note to mention the same.

**Comment by perenstrom** [comment]
@vipulchadda Sorry for answering so late, haven't had the time to look into this. The fields display okay now (just some minor color contrast issues), but the rules don't work at all now it seems. I tried controlling with both a boolean field (which only gave me the option empty or not empty, which is confusing), and a text field. But none managed to hide my fields.

**Comment by perenstrom** [comment]
And nice fallback message for custom field apps!

**Comment by whitelisab** [comment]
@perenstrom, @vipulchadda's fix for issue #702 has been deployed to production. Can you see if this has resolved your issue?

**Comment by perenstrom** [comment]
Yes, it has resolved the issue. Although it's a bit confusing that the rule says "empty" or "not empty" instead of "true" or "false" for boolean fields.

![CleanShot 2024-03-05 at 08 12 53@2x](https://github.com/contentful/marketplace-partner-apps/assets/765759/c58502a0-a6ea-4175-9116-70044d73d682)

But with these changes I think we can start trying it out on our editors, thanks for all the help! ⭐

**Comment by lilbitner** [comment]
@perenstrom I am glad it is working well and appreciate the quick resolutions @vipulchadda ! @vipulchadda do you have any insight around the condition naming i.e "empty" and "not empty" vs "true" and "false"?

**Comment by vipulchadda** [comment]
Currently we support conditions for Short text fields only. All other fields types have `empty` or `not empty` conditions only. We have that in our backlog to support other field types as well.

**Comment by lilbitner** [comment]
Awesome, thank you for clarifying @vipulchadda! I will go ahead and close this issue as all seems to be resolved within it's scope.
