### ISSUE TITLE
[FlexFields] Fields disabled for editing are being shown

### ISSUE THREAD

**Issue by JinHao-L** [contentful/marketplace-partner-apps#931]
**Describe the bug**
Fields disabled for editing are still shown in FlexFields editor page

**To Reproduce**
1. Create a content model with a hidden field (`Disabled Editing field`)
    <img src="https://github.com/contentful/marketplace-partner-apps/assets/52820430/1655f4b7-ffe4-491e-91dd-c3db73163bb4" width="600">

3. `Disabled Editing field` is being shown on FlexFields editor page
    <img src="https://github.com/contentful/marketplace-partner-apps/assets/52820430/423fe66b-cbc6-458c-b912-34f98d232373" width="600">

4. Disabled field is not shown on default editor page
    <img src="https://github.com/contentful/marketplace-partner-apps/assets/52820430/2c048bcc-5617-45c6-b105-c788b81792ae" width="600">

**Expected behavior**
- Disabled field should be hidden on FlexFields editor page by default
- The hidden field should reappear when writer toggle hidden fields
    <img src="https://github.com/contentful/marketplace-partner-apps/assets/52820430/d17ce306-8276-45e0-a04a-fae8142369ec" width="300">

**Additional context**
I did an exploration of contentful SDK API and found that we are able to get the disabled state from SDK Field API [Reference](https://www.contentful.com/developers/docs/extensibility/app-framework/sdk/#getting-disabled-state-of-field)
- `sdk.field.getIsDisabled()`
- `sdk.field.onIsDisabledChanged(callback)`

Not sure if this would be helpful in designing a solution

**Comment by vipulchadda** [comment]
Thank you raising this and giving the additional context. We will look into this and get back to you once fixed.

**Comment by vipulchadda** [comment]
@lilbitner would you be able to help with the PR raised to fix this issue (https://github.com/contentful/marketplace-partner-apps/pull/949)

**Comment by whitelisab** [comment]
@JinHao-L I merged in @vipulchadda's fix and it is now deployed to production. Can you please verify that this issue is now resolved? Thank you!

**Comment by JinHao-L** [comment]
@whitelisab @vipulchadda 
Hi, I have verified that the fix works great! Thanks alot for the prompt fix 👍 

Will close this issue
