### ISSUE TITLE
[Adapt Essentials: Asset Fields] App fails to load

### ISSUE THREAD

**Issue by Toxicom** [contentful/marketplace-partner-apps#941]
**Describe the bug**
Currently installing the **Adapt Essentials: Bulk Asset Fields** app through the Contentful Marketplace leads to the app failing to load.

Issue also opened on the application's repository: https://github.com/adaptdk/adapt-essentials-asset-fields/issues/8

**To Reproduce**
1. Go to Contentful Marketplace
2. Select **Adapt Essentials: Bulk Asset Fields**
3. Install the app
4. Choose environment to install the app to
5. After a loading period, be greeted with an app failed to load window

**Expected behavior**
Application loads successfully and you are able to configure it.

**Screenshots**
<img width="1718" alt="305883338-ab5a5b25-0bbc-41e3-8b7f-7e1db20a61e5" src="https://github.com/contentful/marketplace-partner-apps/assets/69549795/f9c2b2b7-a47c-449e-b420-ae65e74a9a3b">

**Desktop (please complete the following information):**
 - OS: Windows & Mac
 - Browser: Chrome & Firefox
 - Version:
    - Firefox 122.0.1
    - Chrome Version 121.0.6167.185 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by whitelisab** [comment]
Hi @Toxicom! Based on the conversation in this issue in Adapt's repo (https://github.com/adaptdk/adapt-essentials-asset-fields/issues/8), it looks like this has been resolved, so I am going to close this issue.

**Comment by Toxicom** [comment]
Yes, thank you!
